#!/bin/sh

## hyphop ##

# generate img

p=`pwd`

#[ "$p" = "./scripts" ] || {
#	echo "[i] bad working dir )))))"
#	exit 0
#}

cd ../miZy || exit 0

./initrd.img.pack initrd.img.base.music_player_h2
./boot.fel.make-force

cd $p

img_name="firmwares/orange_pi_zero_miZy-music_box-mpd-net-SPI-beta_test.%s"

conf=miZy_spi_image_builder.conf

rm firmwares/*.bin

img_size=8M MMC=1 img_name=$img_name.MMC.hybrid.bin ./miZy_spi_image_builder
img_size=8M       img_name=$img_name.bin ./miZy_spi_image_builder $conf

img_size=16M MMC=1 img_name=$img_name.MMC.hybrid.bin ./miZy_spi_image_builder
img_size=16M       img_name=$img_name.bin ./miZy_spi_image_builder $conf

for f in firmwares/*.bin; do

	n=`basename $f`

	echo "[i] pack gzip > /tmp/$n.gz"
	gzip -c $f > /tmp/$n.gz
#	echo "[i] pack xz   > /tmp/$n.xz"
#	xz -c $f > /tmp/$n.xz

done

cd firmwares

md5sum *.bin > /tmp/name.md5sum

cd ..
