#!/bin/sh

## hyphop ##

d=`dirname $0`

echo $d

[ "$d" = "./scripts" ] || {
	echo "[i] )))))"
	exit 0
}

rm firmwares/*.bin

name=orange_pi_zero_miZy-mini-turbo
name_spi=$name.SPI.%s.bin
name_mmc=$name.MMC.hybrid.%s.bin

conf=miZy_spi_image_builder.conf.fast

MMC=1 img_size=8M img_name=firmwares/$name_mmc \
	./miZy_spi_image_builder $conf

MMC=1 img_size=16M img_name=firmwares/$name_mmc \
	./miZy_spi_image_builder $conf

img_size=8M img_name=firmwares/$name_spi \
	./miZy_spi_image_builder $conf

img_size=16M img_name=firmwares/$name_spi \
	./miZy_spi_image_builder $conf


#find firmwares
for f in firmwares/*.bin; do

	n=`basename $f`

	
	echo "[i] pack gzip > /tmp/$n.gz"
	gzip -c $f > /tmp/$n.gz
	echo "[i] pack xz   > /tmp/$n.xz"
	xz -c $f > /tmp/$n.xz

done

cd firmwares

md5sum *.bin > /tmp/name.md5sum

cd ..
