#!/bin/sh

## hyphop ##

d=`dirname $0`
p=`pwd`

echo $d

[ "$d" = "./scripts" ] || {
	echo "[i] bad working dir )))))"
	exit 0
}

NAME=pulse

cd ../miZy || exit 0

rm -r ,out/initrd.dir

#cmp=lzo ./initrd.img.pack initrd.img.base.spdif
export config=initrd.img.base.$NAME

	./initrd.img.pack.dir

## custom

	echo "BUILD: $(date)" >> ,out/initrd.dir/etc/banner.mod

##

[ "$comp" ] || comp=lzo
#[ "$comp" ] || comp=gzip
#[ "$comp" ] || comp=xz

	./initrd.img.pack.sfs $comp
	
./boot.fel.make-force

cd $p

rm firmwares/*.bin

[ "$board" ] || board=h2

name=orange_pi_zero_${board}_$NAME
name_spi=$name.SPI.%s.bin
name_mmc=$name.MMC.hybrid.%s.bin

conf=miZy_spi_image_builder.conf.fast

MMC=1 img_size=16M img_name=firmwares/$name_mmc \
	./miZy_spi_image_builder $conf

img_size=16M img_name=firmwares/$name_spi \
	./miZy_spi_image_builder $conf

## force
cd ../miZy 
rm ,out/*.sfs
./initrd.img.pack.sfs xz
cd $p

conf=miZy_spi_image_builder.conf

MMC=1 img_size=8M img_name=firmwares/$name_mmc \
	./miZy_spi_image_builder $conf

img_size=8M img_name=firmwares/$name_spi \
	./miZy_spi_image_builder $conf

exit 0

#find firmwares
for f in firmwares/*.bin; do

	n=`basename $f`
	
	echo "[i] pack gzip > /tmp/$n.gz"
	gzip -c $f > /tmp/$n.gz

done

cd firmwares

md5sum *.bin > /tmp/name.md5sum

cd ..

scp firmwares/*.bin root@zeru:/tmp

