#!/bin/sh

## hyphop ##

d=`dirname $0`
p=`pwd`

echo $d

[ "$d" = "./scripts" ] || {
	echo "[i] bad working dir )))))"
	exit 0
}

cd ../miZy || exit 0

rm -r ,out/initrd.dir

#cmp=lzo ./initrd.img.pack initrd.img.base.spdif
export config=initrd.img.base.r1

	./initrd.img.pack.dir

## custom

	echo "BUILD: $(date)" >> ,out/initrd.dir/etc/banner.mod

##

[ "$comp" ] || comp=lzo
[ "$comp" ] || comp=gzip
[ "$comp" ] || comp=xz

	./initrd.img.pack.sfs $comp
	
./boot.fel.make-force

cd $p

rm firmwares/*.bin

name=orange_pi_r1_base
name_spi=$name.SPI.%s.bin
name_mmc=$name.MMC.hybrid.%s.bin

conf=miZy_spi_image_builder.conf.fast

MMC=1 img_size=16M img_name=firmwares/$name_mmc \
	./miZy_spi_image_builder $conf

#find firmwares
for f in firmwares/*.bin; do

	n=`basename $f`
	
	echo "[i] pack gzip > /tmp/$n.gz"
	gzip -c $f > /tmp/$n.gz

done

cd firmwares

md5sum *.bin > /tmp/name.md5sum

cd ..

#scp firmwares/*.bin mizy@r1:/tmp

