#!/bin/sh

set -e 
## hyphop ##

# generate img

p=`pwd`

#[ "$p" = "./scripts" ] || {
#	echo "[i] bad working dir )))))"
#	exit 0
#}

## usage example
# cmp=xz usbnet=5 board=r1 ./scripts/gen_music_box


name="orange_pi_zero_miZy-i2s-rec"
name_spi=$name.SPI.%s.bin
name_mmc=$name.MMC.hybrid.%s.bin
d=firmwares/

conf=miZy_spi_image_builder.conf.fast

for f in $d/*.bin; do
echo "[i] clean $f"
[ -f "$f" ] && rm $f
done

cd ../miZy || exit 0


##cmp=xz ./initrd.img.pack initrd.img.base.video
export config=initrd.img.base.grab

./initrd.img.pack.dir
	
echo "BUILD: $(date)" >> ,out/initrd.dir/etc/banner.mod

shadow_file=initrd.dir-77-uni/etc/shadow \
    ./tools/passw_replace root:jopa > \
    ,out/initrd.dir/etc/shadow

chmod 0600 \
    ,out/initrd.dir/etc/shadow

cat ~/.ssh/id_rsa.pub >> \
    ,out/initrd.dir/etc/dropbear/authorized_keys
##


#[ "$comp" ] || comp=lzo
[ "$comp" ] || comp=gzip
[ "$comp" ] || comp=xz

echo "usbnet: $usbnet"

./initrd.img.pack.sfs $comp

./boot.fel.make-force

cd $p

img_size=16M MMC=1 img_name=$d$name_mmc ./miZy_spi_image_builder $conf
#img_size=16M       img_name=$d$name_spi ./miZy_spi_image_builder $conf


cd $d

md5sum *.bin > /tmp/name.md5sum

cd ..


#[ "$P" ] || P=22
[ "$P" ] && P="-P $P"

[ "$scp" ] && {
echo "scp $P firmwares/*.bin $scp:/tmp"
scp $P firmwares/*.bin $scp:/tmp || {
    echo "[e] fail ssh scp">&2
    exit 1
}
}

[ "$up" ] && {
ping -c1 $scp &&
    ssh $scp /opt/image_write_sd yes && {
    [ "$up" = "2" ] && {
	ssh $scp reboot
    }
    }
}
